

# MySQL Database configuration start --

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO


spring:      
  # User configurations
  security:
    user:
      name: pramukh
      password: swami
 
       
#  datasource:
#    #url: jdbc:mysql://mysql-auth2:3306/oauth2_dev?useSSL=false&createDatabaseIfNotExist=true
#    url: jdbc:mysql://oauth2dev.cwnurgcwlyzw.us-east-1.rds.amazonaws.com:3309/oauth2_dev?useSSL=false&createDatabaseIfNotExist=true
#    username: root
#    password: password123
#    driver-class-name: com.mysql.jdbc.Driver
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
    #initialization-mode: never
#    initialization-mode: never
#    platform: mysql
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      #ddl-auto: validate
      #ddl-auto: create-drop
#      ddl-auto: none
      
# MySQL Database configuration end --

# Custom property used in AuthrizationServerConfig
check-user-scopes: true


# Register this auth server to Eureka server
 
 
      
security:
  oauth2:
    client:
      access-token-validity-seconds: 10400
    authorization:
      jwt:
        key-store: classpath:jwt.jks
        key-alias: jwt
        key-password: password
        key-store-password: password
 
      
      