# MySQL Database configuration start --

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_dev?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
      
# MySQL Database configuration end --

# Custom property used in AuthrizationServerConfig
check-user-scopes: true


# Register this auth server to Eureka server

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
      
security:
  oauth2:
    client:
      access-token-validity-seconds: 10400
      
      